# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[default.limits]
forms = "64 kB"
json = "1000000 KiB"
msgpack = "2 MiB"
"file/jpg" = "32 KiB"
bytes = "64 kB"


[default]
key = "a default app-key"
extra = false
ident = "Rocket"
ip_header = "CF-Connecting-IP"
secret_token_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="


[debug]
address = "127.0.0.1"
port = 4444
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "127.0.0.1"
port = 4444
workers = 12
keep_alive = 5
log_level = "critical"
# NOTE: Don't (!) use this key! Generate your own and keep it private!
#       e.g. via `head -c64 /dev/urandom | base64`
key = "a release app-key"
extra = false
